# Generated by Django 4.1.3 on 2023-01-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Subject', models.TextField(blank=True, max_length=100, null=True)),
                ('Message', models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
